### ISSUE TITLE
wifind fails on first run

### ISSUE THREAD

**Issue by kpcyrd** [raylai/wifind#3]
wifind fails to succeed on the first run, when `$hostname_if` does not exist yet.

```
link $hostname_if, "$hostname_if.orig" or die "link failed: $!";
```

Manually touch(1)ing the file resolves this, otherwise it just fails.

**Comment by raylai** [comment]
Good find. Do you have a patch for this and #4? I've got no time to fix these recently. Cheers!

**Comment by kpcyrd** [comment]
@raylai I'm really not a perl person, but if you agree to review it thorough I'd give it a shot the next few days.

**Comment by raylai** [comment]
Thanks for the report @kpcyrd!
