### ISSUE TITLE
"reject hostile characters" causes warning on open networks

### ISSUE THREAD

**Issue by kpcyrd** [raylai/wifind#4]
When parsing the networks configured, it's always executing this line:

```
# reject hostile characters
if ($ap->{wpakey} =~ /["\\\$]/) {
	warn "malformed wpakey\n";
	next;
}
```

Which causes a warning when `$ap->{wpakey}` is not defined because it's an open network. The connection still succeeds.

**Comment by raylai** [comment]
Fixed, thanks!
